export { addToWatchlist, removeFromWatchlist, getWishListedItemsFromDB } from './axios.wishlist'
export { getCartItemsFromDB, addToCart, removeFromCart, incrementQuantity, decrementQuantity } from './axios.cart'
export { signUpHandler, loginHandler } from './axios.loginSignUp'
export { getproductFromDB } from './axios.getProduct'
export { addressHandler } from './axios.address'